config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    put "tasks/delete_all"=>"tasks#delete_all"
    resources :tasks do 
       collection { post :import }
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'projects#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :user
  validates :name, presence: true


  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end
  
  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete?}
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete?}
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?
   ((total_complete.to_f/total_tasks)*100).round
  end

  def total_complete
    tasks.select{|task| task.complete?}.count
  end

  def total_tasks
   tasks.count
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  has_one_attached :file
  validates :status, inclusion: { in: %w[not-started in-progress complete] }

  FILE_VALIDATIONS = {
    content_types: ['text/csv']

  }.freeze
  STATUS_OPTIONS = [
    ['Not Started', 'not-started'],
    ['In Progress', 'in-progress'],
    %w[Complete complete]
  ].freeze
  

  def self.to_csv
    header_attributes = %w[Name Description Status]
    CSV.generate(headers: true) do |csv|
      csv << header_attributes
      all.each do |item|
        csv << item.attributes.values_at('name', 'description', 'status')
      end
    end
  end

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

  def complete?
    status ==  'complete'
  end

  def not_started?
    status ==  'not-started'
  end

  def in_progress?
    status ==  'in-progress'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = @project.tasks.build
    @current_tasks = @project.tasks.offset(pagination).limit(2)
    
    
    respond_to do |format|
      format.html
      format.csv{send_data @project.tasks.to_csv,
      filename: @project.name + " Tasks.csv",
      type: 'text/csv; charset=utf-8' }
    end
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # def import
  #  @import_response =  current_user.projects.import(params[:file])
  # end
  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { redirect_to @project,  notice: 'Project was not successfully updated.' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
   
  private
    # Use callbacks to share common setup or constraints between actions.
    def project
      @project = current_user.projects.find(params[:id])
    end

    def pagination
      if params[:pagination]== nil || params[:pagination].to_i < 0
        @pagination = 0
      else
        @pagination = params[:pagination]
      end
    end
    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end   
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: %i[show edit update destroy]

  # GET projects/1/tasks
  def index
    @tasks = @project.tasks
  end

  def import
    if !params[:file].nil?
      if !Task::FILE_VALIDATIONS[:content_types].include? params[:file].content_type
        flash[:alert] = "ERROR: File uploaded was not a CSV file"
      else
        @project.tasks.import(params[:file], @project)
        correct_header = %w[name description status]
        header_from_file = CSV.foreach(params[:file].path).first.map(&:downcase)

        begin
          if header_from_file != correct_header
            flash[:alert] = "ERROR: The header information in the file needs to be Name, Description, Status"
          else
            CSV.foreach(params[:file].path, headers: true, row_sep: :auto, col_sep: ',', header_converters: :symbol) do |row|
              if row[:status] == '0'
                row[:status] = 'not-started'
              elsif row[:status] == '1'
                row[:status] = 'in-progress'
              elsif row[:status] == '2'
                row[:status] = 'complete'
              else
                row[:status] = 'not-started'
              end
              @project.tasks.create! row.to_hash
            end
          end
        rescue CSV::MalformedCSVError
          flash[:alert] = "ERROR: CSV file is not formatted correctly. Please regenerate CSV file"
        end
      end
    else
      flash[:alert] = "ERROR: No File was uploaded"
    end
    redirect_to(project_path(@project))
  end

  # GET projects/1/tasks/1
  def show; end

  # GET projects/1/tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET projects/1/tasks/1/edit
  def edit; end

  # POST projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to([@task.project])
    else
      render action: 'new'
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @task.update_attributes(task_params)
      redirect_to([@task.project])
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
    @task.destroy

    redirect_to @project
  end

  def delete_all
    @project.tasks.destroy_all
    redirect_to @project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def task_params
    params.require(:task).permit(:name, :description, :status, :project_id, :file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplePm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" >
   <script type="module" src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<% if user_signed_in? %>
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">Simple Project</a>
  <form class="form-inline">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success'%>
  </form>
</nav>
<% end %>
  <body class='bg-light'>
  <div class="container pt-5">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

        <%= yield %>
  </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
 <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'%>
  </div>
  <div class="actions d-flex">
    <%= link_to 'Back', projects_path, class: 'btn btn-secondary mb-3 p-2' %>
    <%= form.submit class: 'btn btn-primary  mb-3  ml-auto p-2' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
    <span>Editing Project</span>
    </h2>
     <%= render 'form', project: @project %>
    </div>
</div>

app/views/projects/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title d-flex justify-content-between mb-4">
      <span>Projects</span>
      <%= link_to 'New Project', new_project_path, class: "btn btn-primary" %>
    </h2>
    <% @projects.each do |project| %>
      <%= link_to 'Edit', edit_project_path(project), class: 'mb-3  mr-auto p-2 btn btn-light'%>
      <%= link_to 'Destroy',project, method: :delete, class: 'mb-3  mr-auto p-2 btn btn-dark', data: { confirm: 'Are you sure?' } %>
      <%= link_to project, class: 'text-decoration-none' do %>
        <div class="card project-card mb-3">
          <div class="card-body">
            <div class="mb-3">
              <span class="badge badge-<%=project.badge_color %>" >
                <%= project.status %></span>
              <span class="text-secondary">
                <small>
                  <%= project.percent_complete %>% complete
                  (<%= project.total_complete %>/<%= project.total_tasks %> tasks)
                </small>
              </span>
            </div>
            <div class="actions d-flex">
              <div class="mb-3  mr-auto p-2">
                <h5 class="card-title text-dark"> <%= project.name %> </b></h5>
              <p class="text-secondary"> <%= project.description%> </p>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  <%end%>
</div>
</div>

app/views/projects/new.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
    <span>New Project</span>
    </h2>
        <%= render 'form', project: @project %>

</div>
</div>

app/views/projects/show.html.erb
<div class="card">
  <div class="card-body">
    <h2 class= "card-title d-flex justify-content-between mb-4">
      <span> <%= @project.name %> </span>
      <div class="d-flex justify-content-between">
        <%= form_tag import_project_tasks_path(@project), :multipart => true do %>
          <%= file_field_tag :file, class: 'btn btn-info  mb-3  ml-auto p-2'  %>
          <%= submit_tag "Generate Tasks", class: 'btn btn-info  mb-3  ml-auto p-2'  %>
          <% if @project.tasks.count < 1%>
              <%= link_to 'Export', project_path(format: :csv), class: 'btn btn-success mb-3 ml-auto p-2', :id => "disabled_btn" %>
          <% else %>  
             <%= link_to 'Export', project_path(format: :csv), class: 'btn btn-success mb-3 ml-auto p-2' %>
          <% end %>
        <% end %>
      </div>
    </h2>
    <span><%= @project.description %> </span>
    <br/>
    <span>***NOTE***</span>
    <br/>
    <span>The CSV File needs to have the header of ::  Name, Description, Status</span>
    <br/>
    <br/>
    <% if @project.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@project.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-4">
      <h6> Add Task </h6>
      <%= form_with(model: [@task.project, @task]) do |f| %>
        <% if @task.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
            <ul>
              <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.hidden_field :status, value: 'not-started' %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: "Enter Task Name..." %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
    <h4> Tasks </h4>
    <% @current_tasks.each do |task| %>
      <% if task.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <span class="badge badge-<%=task.badge_color %> mb-3"> <%= task.status%></span>
              <div>
                <%= link_to 'Edit', edit_project_task_path(task.project, task) , class: 'btn btn-light btn-sm' %>
                <%= link_to 'Destroy', [task.project, task] , method: :delete, data:{
              confirm: 'Are you sure?'}, class: 'btn btn-dark btn-sm' %>
              </div>
            </div>
            <h5 class="card-title mb-2">
              <span><%= task.name %> </span>
            </h5>
            <% if task.description == nil || task.description == "" %>
              <p>No Description</p>
            <% end %>
            <p> <%= task.description %> </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<hr>
<div class="actions d-flex">
  <%= link_to 'Main', projects_path, class: 'btn btn-secondary mb-5 p-2'%>
  <div> 
      <% backPage = @pagination.to_i - 2 %>
      <% nextPage = @pagination.to_i + 2 %>
      
      <% if @pagination == nil || @pagination == 0 %>
        <%= link_to 'Back', project_path(:pagination => backPage), class: 'btn btn-warning mb-5 p-2', :id => "disabled_btn" %> 
     <% else %>
        <%= link_to 'Back', project_path(:pagination => backPage), class: 'btn btn-warning mb-5 p-2'%>
    <% end %>
    <% if @current_tasks.count < 2%>
        <%= link_to 'Next', project_path(:pagination => nextPage), class: 'btn btn-warning mb-5 p-2', :id => "disabled_btn" %> 
    <% else %>
     <%= link_to 'Next', project_path( :pagination => nextPage), class: 'btn btn-warning mb-5 p-2'%>
  <% end %>
 </div>
  <div class="ml-auto p-2">
      <% if @project.tasks.count < 1%>
              <%= link_to 'Destroy All Tasks',  
              project_tasks_delete_all_path(@project.id),
              data: { confirm: 'Are you sure you want to destroy all the tasks' } , 
             class: 'btn btn-danger mb-3 p-2',
              :id => "disabled_btn" %> 
      <% else %>  
              <%= link_to 'Destroy All Tasks',  
              project_tasks_delete_all_path(@project.id),  method: :put,
              data: { confirm: 'Are you sure you want to destroy all the tasks' } , 
             class: 'btn btn-danger mb-3 p-2'%> 
      <% end %>
   </div>
</div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task.project, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: 'form-control'%>
    <br/>
    <%= f.label :description %><br />
    <%= f.text_field :description, class: 'form-control'%>

  </div>
    <div class="form-group">
    <%= f.label :status %><br />
    <%= f.select :status, Task::STATUS_OPTIONS, {}, class: 'form-control' %>
  </div>
   <div class="actions d-flex">
    <%= link_to 'Back', @project, class: 'btn btn-secondary mb-3 p-2' %>
    <%= f.submit class: 'btn btn-primary  mb-3  ml-auto p-2' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
    <span>Editing Task</span>
    </h2> 
     <%= render 'form' %>
    </div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.description %></td>
    <td><%= task.status %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task] %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_task_path(params[:project_id]) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tasks_path(@task.project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Status:</b>
  <%= @task.status %>
</p>

<p>
  <b>Project:</b>
  <%= @task.project %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %> |
<%= link_to 'Back', project_tasks_path(@task.project) %>